# Site
name: 'azzyjk의 Dev Note'
title: 'azzyjk의 개발 일기'
description: "azzyjk's dev note that start from basic"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
# baseurl: /mediumish-theme-jekyll
baseurl: 'https://azzyjk.github.io'
google_analytics: 'UA-171557469-1'
disqus: 'azzyjk'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ['_pages']
permalink: /:title/

# Authors
authors:
  JJW:
    name: JeongJunwon
    display_name: azzyjk
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: azzyjk@naver.com
    web: https://www.github.com/azzyjk
    # twitter: https://twitter.com/wowthemesnet
    description: '아무거나 다 해보는 대학생'
  # john:
  #   name: John
  #   display_name: John
  #   avatar: 'assets/images/avatar.png'
  #   gravatar: b1cc14991db7a456fcd761680bbc8f81
  #   email: wowthemesnet@gmail.com
  #   web: https://www.wowthemes.net
  #   twitter: https://twitter.com/wowthemesnet
  #   description: 'This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages.'

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # block:
    #   line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: 'disabled'
adsense-data-ad-client: 'ca-pub-3412143450191416'
adsense-data-ad-slot: '1363087678'

# Lazy Images ("enabled" or "disabled")
lazyimages: 'disabled'

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
